### ISSUE TITLE
v0.5.1 docs are broken

### ISSUE THREAD

**Issue by esemeniuc** [0xdeafbeef/axum-jrpc#15]
No docs available for v0.5.x, can see version switcher at https://docs.rs/axum-jrpc/0.4.0/axum_jrpc/

**Comment by 0xdeafbeef** [comment]
Fixed by a14496bc876b1c75345ba04c5bc31323cb71895f for 0.6.x and by 9b688e6923deac8be38bd1f4605e0b496eb97033 for 0.5.x
