### ISSUE TITLE
anyhow as an application error

### ISSUE THREAD

**Issue by nkconnor** [0xdeafbeef/axum-jrpc#4]
https://github.com/0xdeafbeef/axum-jrpc/blob/c237d6b7280bb772978748f6c29c92e69bb04243/src/error.rs#L95

I think `anyhow::Error` maybe fits into an application error mentioned at the bottom of [5.1 (copied inline below)](https://www.jsonrpc.org/specification#error_object). By remainder of the space, though, do they mean the entire integer range?

code | message | meaning
-- | -- | --
-32700 | Parse error | Invalid JSON was received by the server.An error occurred on the server while parsing the JSON text.
-32600 | Invalid Request | The JSON sent is not a valid Request object.
-32601 | Method not found | The method does not exist / is not available.
-32602 | Invalid params | Invalid method parameter(s).
-32603 | Internal error | Internal JSON-RPC error.
-32000 to -32099 | Server error | Reserved for implementation-defined server-errors.

<p style="margin: 0px 0px 9px; font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 13px; line-height: 18px; color: rgb(51, 51, 51); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">The remainder of the space is available for application defined errors.</p>

**Comment by 0xdeafbeef** [comment]
Oh, I misread docs. So I'll set 1 as code for axum
